import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import Alert from "@mui/material/Alert";
import { AvailableProduct, AvailableProductSchema } from "~/models/Product";
import { Formik, Field, FormikProps, Form } from "formik";
import TextField from "~/components/Form/TextField";
import { useNavigate, useParams } from "react-router-dom";
import PaperLayout from "~/components/PaperLayout/PaperLayout";
import Typography from "@mui/material/Typography";
import React from "react";
import {
  useAvailableProduct,
  useInvalidateAvailableProducts,
  useRemoveProductCache,
  useUpsertAvailableProduct,
} from "~/queries/products";

// Default empty product values for creating new products
const initialValues: AvailableProduct = AvailableProductSchema.cast({});

/**
 * PageProductForm - Form for creating and editing products
 * 
 * This component handles both creating new products and editing existing ones:
 * - When accessed via /admin/product-form (no ID) → Create mode
 * - When accessed via /admin/product-form/:id → Edit mode
 * 
 * Form fields:
 * - Title: Product name (required)
 * - Description: Product description (required)
 * - Price: Product price in cents (required)
 * - Count: Stock quantity (required)
 * - Image: URL to product image (optional, supports Unsplash URLs)
 * 
 * On successful save:
 * - Creates/updates product in DynamoDB via API
 * - Invalidates product cache to refresh lists
 * - Navigates back to admin products page
 */
export default function PageProductForm() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>(); // Get product ID from URL params (undefined for new products)
  const invalidateAvailableProducts = useInvalidateAvailableProducts(); // Refresh product lists after save
  const removeProductCache = useRemoveProductCache(); // Clear specific product cache
  const { data, isLoading } = useAvailableProduct(id); // Load existing product data for editing
  const { mutateAsync: upsertAvailableProduct } = useUpsertAvailableProduct(); // API call to save product
  
  // State for success message display
  const [showSuccess, setShowSuccess] = React.useState(false);
  const [successMessage, setSuccessMessage] = React.useState('');
  
  // Handle form submission for both create and update operations
  const onSubmit = (values: AvailableProduct) => {
    // Validate and format form values using Yup schema
    const formattedValues = AvailableProductSchema.cast(values);
    
    // Determine if we're creating or updating based on presence of ID
    const productToSave = id
      ? {
          ...formattedValues,
          id, // Include existing ID for updates
        }
      : formattedValues; // No ID for new products (will be generated by backend)
    
    // Submit to API and handle success
    return upsertAvailableProduct(productToSave, {
      onSuccess: () => {
        // Show success message based on operation type
        const message = id ? 'Product updated successfully!' : 'Product created successfully!';
        setSuccessMessage(message);
        setShowSuccess(true);
        
        invalidateAvailableProducts(); // Refresh product lists so new/updated product appears
        removeProductCache(id); // Clear cached product data
        
        // Navigate back to admin page after a short delay to show success message
        setTimeout(() => {
          navigate("/admin/products");
        }, 2000); // 2 second delay to show success message
      },
    });
  };

  return (
    <PaperLayout>
      {/* Dynamic title based on create vs edit mode */}
      <Typography component="h1" variant="h4" align="center" mb={2}>
        {id ? "Edit product" : "Create new product"}
      </Typography>
      
      {/* Success message alert - shows after successful product creation/update */}
      {showSuccess && (
        <Alert severity="success" sx={{ mb: 2 }}>
          {successMessage}
        </Alert>
      )}
      
      {isLoading ? (
        <>Loading...</> // Show loading state while fetching existing product data
      ) : (
        <Formik
          initialValues={data ?? initialValues} // Use existing data for editing, empty values for creating
          validationSchema={AvailableProductSchema} // Yup validation schema
          onSubmit={onSubmit}
        >
          {({ dirty, isSubmitting }: FormikProps<AvailableProduct>) => (
            <Form autoComplete="off">
              <Grid container spacing={2}>
                {/* Product title field - required for all products */}
                <Grid item xs={12}>
                  <Field
                    component={TextField}
                    name="title"
                    label="Title"
                    fullWidth
                    autoComplete="off"
                    required
                  />
                </Grid>
                
                {/* Product description field - supports multiline text */}
                <Grid item xs={12}>
                  <Field
                    component={TextField}
                    name="description"
                    label="Description"
                    fullWidth
                    autoComplete="off"
                    multiline
                    required
                  />
                </Grid>
                
                {/* Price field - stored as cents in database */}
                <Grid item xs={12} sm={4}>
                  <Field
                    component={TextField}
                    name="price"
                    label="Price ($)"
                    fullWidth
                    autoComplete="off"
                    required
                  />
                </Grid>
                
                {/* Stock count field - inventory quantity */}
                <Grid item xs={12} sm={4}>
                  <Field
                    component={TextField}
                    name="count"
                    label="Count"
                    fullWidth
                    autoComplete="off"
                    required
                  />
                </Grid>
                
                {/* Image URL field - optional, supports Unsplash and other image URLs */}
                <Grid item xs={12}>
                  <Field
                    component={TextField}
                    name="image"
                    label="Image URL"
                    fullWidth
                    autoComplete="off"
                    placeholder="https://images.unsplash.com/..."
                  />
                </Grid>
                
                {/* Form action buttons */}
                <Grid item container xs={12} justifyContent="space-between">
                  {/* Cancel button - returns to admin page without saving */}
                  <Button
                    color="primary"
                    onClick={() => navigate("/admin/products")}
                  >
                    Cancel
                  </Button>
                  
                  {/* Save button - submits form and creates/updates product */}
                  <Button
                    type="submit"
                    variant="contained"
                    color="primary"
                    disabled={!dirty || isSubmitting} // Disabled if no changes or currently submitting
                  >
                    Save Product
                  </Button>
                </Grid>
              </Grid>
            </Form>
          )}
        </Formik>
      )}
    </PaperLayout>
  );
}
